version: '3'
services:
  mysql:
    image: mysql
    container_name: burger_graalvm_api.mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'burger_graalvm_api'
      MYSQL_USER: 'burger_api_user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:mysql://mysql -schemas=burger_graalvm_api -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql
