
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/burger_api?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true'
    username: 'burger_api_user'
    password: '1234'
    hikari:
      pool-name: '${spring.datasource.username}'
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 30
      leak-detection-threshold: 60000
      connection-init-sql: 'SELECT 1'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hibernate.dialect: 'org.hibernate.dialect.MySQL57InnoDBDialect'
        hibernate.connection.release_mode: 'after_transaction'
        hibernate.enable_lazy_load_no_trans: true
        hibernate.format_sql: true

server:
  port: 8080
